### ISSUE TITLE
zh:zstack:znp: Skip bootloader for CC2652/CC1352 [2024-05-30 21:52:09] error: 	z2m: Error while starting zigbee-herdsman [2024-05-30 21:52:09] error: 	z2m: Failed to start zigbee [2024-05-30 21:52:09] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions [2024-05-30 21:52:09] error: 	z2m: Exiting... [2024-05-30 21:52:09] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)     at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:101:27)     at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:124:29)     at Zigbee.start (/app/lib/zigbee.ts:62:27)     at Controller.start (/app/lib/controller.ts:109:27)     at start (/app/index.js:107:5)

### ISSUE THREAD

**Issue by Frend13** [xyzroe/XZG#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Frend13** [comment]
Перестал запускається z2mqtt в home assistant после обновлений.Haos 2024.5.5.ос android, браузер Chrome.Ошибку представили.модель uzg-01.fw ,версія ESP32-D0WDQ6,HW версія CC2652P7
